name = "NCTiles"
uuid = "4c1fdd90-559f-11e9-1abf-07ceafc4ffc0"
authors = ["gaelforget <gforget@mit.edu>"]
version = "0.1.4"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
MeshArrays = "cb8c808f-1acf-59a3-9d2b-6e38d009f683"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
NetCDF = "30363a11-5582-574a-97bb-aa9a979735b9"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
julia = "0.7, 1"
